[package]
name = "comparador"
version = "0.1.0"
authors = ["Luiz fabiano silva samuel <85593514+LuizGafanhotos@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
